<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/UrlGenerator.php */
class __TwigTemplate_e7bae2cc5019a717c7a831707a6481dc70bda13e71fe72eec1f74e6432ca966f extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/UrlGenerator.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/UrlGenerator.php"));

        // line 1
        echo "<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'home' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::home'], [], [['text', '/']], [], []],
    'create' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::form'], [], [['text', '/article/news']], [], []],
    'edit' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::form'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'security_dashboard' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::dashboard'], [], [['text', '/dashboard']], [], []],
    'articles' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::articles'], [], [['text', '/articles']], [], []],
    'sitemap' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::sitemap'], [], [['text', '/sitemap.xml']], [], []],
    'show' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'article_like' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::like'], [], [['text', '/like'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'show_user' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::showUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/dashboard/user']], [], []],
    'delete_comment' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::deleteCommentUserById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/remove/comment']], [], []],
    'success_com' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::SuccessCom'], [], [['text', '/Success_com']], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::removeUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/dashboard/user/delete']], [], []],
    'my_articles' => [['name'], ['_controller' => 'App\\\\Controller\\\\ArticleController::showArticlesByUser'], [], [['text', '/articles'], ['variable', '/', '[^/]++', 'name', true], ['text', '/user']], [], []],
    'contact_user' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::contactUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/contact/user']], [], []],
    'contact' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::contact'], [], [['text', '/contact']], [], []],
    'error_contact' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::errorContact'], [], [['text', '/contact/error/mail']], [], []],
    'success' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::Success'], [], [['text', '/Success']], [], []],
    'delete_article' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::deleteArticleById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/remove/article']], [], []],
    'security_registration' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::register'], [], [['text', '/inscription']], [], []],
    'security_login' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::login'], [], [['text', '/login']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'rgpd' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::rgpd'], [], [['text', '/RGPD']], [], []],
    'mention_legal' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::mentions'], [], [['text', '/mentions']], [], []],
    '404' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::notFound'], [], [['text', '/404']], [], []],
    'logout' => [[], [], [], [['text', '/security_logout']], [], []],
];
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/UrlGenerator.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'home' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::home'], [], [['text', '/']], [], []],
    'create' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::form'], [], [['text', '/article/news']], [], []],
    'edit' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::form'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'security_dashboard' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::dashboard'], [], [['text', '/dashboard']], [], []],
    'articles' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::articles'], [], [['text', '/articles']], [], []],
    'sitemap' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::sitemap'], [], [['text', '/sitemap.xml']], [], []],
    'show' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'article_like' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::like'], [], [['text', '/like'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'show_user' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::showUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/dashboard/user']], [], []],
    'delete_comment' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::deleteCommentUserById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/remove/comment']], [], []],
    'success_com' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::SuccessCom'], [], [['text', '/Success_com']], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::removeUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/dashboard/user/delete']], [], []],
    'my_articles' => [['name'], ['_controller' => 'App\\\\Controller\\\\ArticleController::showArticlesByUser'], [], [['text', '/articles'], ['variable', '/', '[^/]++', 'name', true], ['text', '/user']], [], []],
    'contact_user' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::contactUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/contact/user']], [], []],
    'contact' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::contact'], [], [['text', '/contact']], [], []],
    'error_contact' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::errorContact'], [], [['text', '/contact/error/mail']], [], []],
    'success' => [[], ['_controller' => 'App\\\\Controller\\\\ArticleController::Success'], [], [['text', '/Success']], [], []],
    'delete_article' => [['id'], ['_controller' => 'App\\\\Controller\\\\ArticleController::deleteArticleById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/remove/article']], [], []],
    'security_registration' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::register'], [], [['text', '/inscription']], [], []],
    'security_login' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::login'], [], [['text', '/login']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'rgpd' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::rgpd'], [], [['text', '/RGPD']], [], []],
    'mention_legal' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::mentions'], [], [['text', '/mentions']], [], []],
    '404' => [[], ['_controller' => 'App\\\\Controller\\\\SecurityController::notFound'], [], [['text', '/404']], [], []],
    'logout' => [[], [], [], [['text', '/security_logout']], [], []],
];
", "var/cache/dev/UrlGenerator.php", "/var/www/public/DevLaon/templates/var/cache/dev/UrlGenerator.php");
    }
}
