<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerEObV2MS/getSecurity_Csrf_TokenManagerService.php */
class __TwigTemplate_ff0d3ec08d1cc7bd71ff457d8446a22d2e02df8012eaa493274c05fab5a125fe extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getSecurity_Csrf_TokenManagerService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getSecurity_Csrf_TokenManagerService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'security.csrf.token_manager' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/security-csrf/CsrfTokenManagerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-csrf/CsrfTokenManager.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-csrf/TokenGenerator/TokenGeneratorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-csrf/TokenGenerator/UriSafeTokenGenerator.php';

return \$this->services['security.csrf.token_manager'] = new \\Symfony\\Component\\Security\\Csrf\\CsrfTokenManager(new \\Symfony\\Component\\Security\\Csrf\\TokenGenerator\\UriSafeTokenGenerator(), (\$this->privates['security.csrf.token_storage'] ?? \$this->load('getSecurity_Csrf_TokenStorageService.php')), (\$this->services['request_stack'] ?? (\$this->services['request_stack'] = new \\Symfony\\Component\\HttpFoundation\\RequestStack())));
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerEObV2MS/getSecurity_Csrf_TokenManagerService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'security.csrf.token_manager' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/security-csrf/CsrfTokenManagerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-csrf/CsrfTokenManager.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-csrf/TokenGenerator/TokenGeneratorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-csrf/TokenGenerator/UriSafeTokenGenerator.php';

return \$this->services['security.csrf.token_manager'] = new \\Symfony\\Component\\Security\\Csrf\\CsrfTokenManager(new \\Symfony\\Component\\Security\\Csrf\\TokenGenerator\\UriSafeTokenGenerator(), (\$this->privates['security.csrf.token_storage'] ?? \$this->load('getSecurity_Csrf_TokenStorageService.php')), (\$this->services['request_stack'] ?? (\$this->services['request_stack'] = new \\Symfony\\Component\\HttpFoundation\\RequestStack())));
", "var/cache/dev/ContainerEObV2MS/getSecurity_Csrf_TokenManagerService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerEObV2MS/getSecurity_Csrf_TokenManagerService.php");
    }
}
