<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerRWJYAMq/get_ServiceLocator_LedKf08Service.php */
class __TwigTemplate_2cc47d16dc500bc5966a2b617c55fbbcd7a3e47d8cc1310312fc5f930bb8fa58 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/get_ServiceLocator_LedKf08Service.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/get_ServiceLocator_LedKf08Service.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LedKf08' shared service.

return \$this->privates['.service_locator.LedKf08'] = new \\Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator(\$this->getService, [
    'repo' => ['privates', 'App\\\\Repository\\\\ArticleRepository', 'getArticleRepositoryService.php', true],
    'repoCategory' => ['privates', 'App\\\\Repository\\\\CategoryRepository', 'getCategoryRepositoryService.php', true],
], [
    'repo' => 'App\\\\Repository\\\\ArticleRepository',
    'repoCategory' => 'App\\\\Repository\\\\CategoryRepository',
]);
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerRWJYAMq/get_ServiceLocator_LedKf08Service.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LedKf08' shared service.

return \$this->privates['.service_locator.LedKf08'] = new \\Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator(\$this->getService, [
    'repo' => ['privates', 'App\\\\Repository\\\\ArticleRepository', 'getArticleRepositoryService.php', true],
    'repoCategory' => ['privates', 'App\\\\Repository\\\\CategoryRepository', 'getCategoryRepositoryService.php', true],
], [
    'repo' => 'App\\\\Repository\\\\ArticleRepository',
    'repoCategory' => 'App\\\\Repository\\\\CategoryRepository',
]);
", "var/cache/dev/ContainerRWJYAMq/get_ServiceLocator_LedKf08Service.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerRWJYAMq/get_ServiceLocator_LedKf08Service.php");
    }
}
