<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerRWJYAMq/getCacheWarmerService.php */
class __TwigTemplate_3aca9019667f9ac6b1bf982bf96b155c62814ea3b90dbb400e70a7b314f44d7c extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getCacheWarmerService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getCacheWarmerService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache_warmer' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php';

return \$this->services['cache_warmer'] = new \\Symfony\\Component\\HttpKernel\\CacheWarmer\\CacheWarmerAggregate(new RewindableGenerator(function () {
    yield 0 => (\$this->privates['validator.mapping.cache_warmer'] ?? \$this->load('getValidator_Mapping_CacheWarmerService.php'));
    yield 1 => (\$this->privates['translation.warmer'] ?? \$this->load('getTranslation_WarmerService.php'));
    yield 2 => (\$this->privates['router.cache_warmer'] ?? \$this->load('getRouter_CacheWarmerService.php'));
    yield 3 => (\$this->privates['annotations.cache_warmer'] ?? \$this->load('getAnnotations_CacheWarmerService.php'));
    yield 4 => (\$this->privates['serializer.mapping.cache_warmer'] ?? \$this->load('getSerializer_Mapping_CacheWarmerService.php'));
    yield 5 => (\$this->privates['doctrine.orm.proxy_cache_warmer'] ?? \$this->load('getDoctrine_Orm_ProxyCacheWarmerService.php'));
    yield 6 => (\$this->privates['twig.cache_warmer'] ?? \$this->load('getTwig_CacheWarmerService.php'));
    yield 7 => (\$this->privates['twig.template_cache_warmer'] ?? \$this->load('getTwig_TemplateCacheWarmerService.php'));
}, 8), true, (\$this->targetDirs[0].'/srcApp_KernelDevDebugContainerDeprecations.log'));
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerRWJYAMq/getCacheWarmerService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache_warmer' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php';

return \$this->services['cache_warmer'] = new \\Symfony\\Component\\HttpKernel\\CacheWarmer\\CacheWarmerAggregate(new RewindableGenerator(function () {
    yield 0 => (\$this->privates['validator.mapping.cache_warmer'] ?? \$this->load('getValidator_Mapping_CacheWarmerService.php'));
    yield 1 => (\$this->privates['translation.warmer'] ?? \$this->load('getTranslation_WarmerService.php'));
    yield 2 => (\$this->privates['router.cache_warmer'] ?? \$this->load('getRouter_CacheWarmerService.php'));
    yield 3 => (\$this->privates['annotations.cache_warmer'] ?? \$this->load('getAnnotations_CacheWarmerService.php'));
    yield 4 => (\$this->privates['serializer.mapping.cache_warmer'] ?? \$this->load('getSerializer_Mapping_CacheWarmerService.php'));
    yield 5 => (\$this->privates['doctrine.orm.proxy_cache_warmer'] ?? \$this->load('getDoctrine_Orm_ProxyCacheWarmerService.php'));
    yield 6 => (\$this->privates['twig.cache_warmer'] ?? \$this->load('getTwig_CacheWarmerService.php'));
    yield 7 => (\$this->privates['twig.template_cache_warmer'] ?? \$this->load('getTwig_TemplateCacheWarmerService.php'));
}, 8), true, (\$this->targetDirs[0].'/srcApp_KernelDevDebugContainerDeprecations.log'));
", "var/cache/dev/ContainerRWJYAMq/getCacheWarmerService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerRWJYAMq/getCacheWarmerService.php");
    }
}
