<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerRWJYAMq/getForm_RegistryService.php */
class __TwigTemplate_43adb47c97d632994be9e818021d18469666f4bdd608043a20cfb27949c7ef4f extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getForm_RegistryService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getForm_RegistryService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/form/FormRegistryInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/FormRegistry.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactory.php';

return \$this->privates['form.registry'] = new \\Symfony\\Component\\Form\\FormRegistry([0 => new \\Symfony\\Component\\Form\\Extension\\DependencyInjection\\DependencyInjectionExtension(new \\Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator(\$this->getService, [
    'App\\\\Form\\\\ArticleType' => ['privates', 'App\\\\Form\\\\ArticleType', 'getArticleTypeService.php', true],
    'App\\\\Form\\\\CommentType' => ['privates', 'App\\\\Form\\\\CommentType', 'getCommentTypeService.php', true],
    'App\\\\Form\\\\RegistrationType' => ['privates', 'App\\\\Form\\\\RegistrationType', 'getRegistrationTypeService.php', true],
    'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\Type\\\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService.php', true],
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService.php', true],
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FileType' => ['services', 'form.type.file', 'getForm_Type_FileService.php', true],
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService.php', true],
], [
    'App\\\\Form\\\\ArticleType' => '?',
    'App\\\\Form\\\\CommentType' => '?',
    'App\\\\Form\\\\RegistrationType' => '?',
    'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\Type\\\\EntityType' => '?',
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\ChoiceType' => '?',
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FileType' => '?',
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FormType' => '?',
]), ['Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FormType' => new RewindableGenerator(function () {
    yield 0 => (\$this->privates['form.type_extension.form.transformation_failure_handling'] ?? \$this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 1 => (\$this->privates['form.type_extension.form.http_foundation'] ?? \$this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 2 => (\$this->privates['form.type_extension.form.validator'] ?? \$this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 3 => (\$this->privates['form.type_extension.upload.validator'] ?? \$this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 4 => (\$this->privates['form.type_extension.csrf'] ?? \$this->load('getForm_TypeExtension_CsrfService.php'));
    yield 5 => (\$this->privates['form.type_extension.form.data_collector'] ?? \$this->load('getForm_TypeExtension_Form_DataCollectorService.php'));
}, 6), 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => (\$this->privates['form.type_extension.repeated.validator'] ?? (\$this->privates['form.type_extension.repeated.validator'] = new \\Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => (\$this->privates['form.type_extension.submit.validator'] ?? (\$this->privates['form.type_extension.submit.validator'] = new \\Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension()));
}, 1)], new RewindableGenerator(function () {
    yield 0 => (\$this->privates['form.type_guesser.validator'] ?? \$this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => (\$this->privates['form.type_guesser.doctrine'] ?? \$this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))], new \\Symfony\\Component\\Form\\Extension\\DataCollector\\Proxy\\ResolvedTypeFactoryDataCollectorProxy(new \\Symfony\\Component\\Form\\ResolvedFormTypeFactory(), (\$this->privates['data_collector.form'] ?? \$this->getDataCollector_FormService())));
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerRWJYAMq/getForm_RegistryService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/form/FormRegistryInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/FormRegistry.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactory.php';

return \$this->privates['form.registry'] = new \\Symfony\\Component\\Form\\FormRegistry([0 => new \\Symfony\\Component\\Form\\Extension\\DependencyInjection\\DependencyInjectionExtension(new \\Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator(\$this->getService, [
    'App\\\\Form\\\\ArticleType' => ['privates', 'App\\\\Form\\\\ArticleType', 'getArticleTypeService.php', true],
    'App\\\\Form\\\\CommentType' => ['privates', 'App\\\\Form\\\\CommentType', 'getCommentTypeService.php', true],
    'App\\\\Form\\\\RegistrationType' => ['privates', 'App\\\\Form\\\\RegistrationType', 'getRegistrationTypeService.php', true],
    'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\Type\\\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService.php', true],
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService.php', true],
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FileType' => ['services', 'form.type.file', 'getForm_Type_FileService.php', true],
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService.php', true],
], [
    'App\\\\Form\\\\ArticleType' => '?',
    'App\\\\Form\\\\CommentType' => '?',
    'App\\\\Form\\\\RegistrationType' => '?',
    'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\Type\\\\EntityType' => '?',
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\ChoiceType' => '?',
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FileType' => '?',
    'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FormType' => '?',
]), ['Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FormType' => new RewindableGenerator(function () {
    yield 0 => (\$this->privates['form.type_extension.form.transformation_failure_handling'] ?? \$this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 1 => (\$this->privates['form.type_extension.form.http_foundation'] ?? \$this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 2 => (\$this->privates['form.type_extension.form.validator'] ?? \$this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 3 => (\$this->privates['form.type_extension.upload.validator'] ?? \$this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 4 => (\$this->privates['form.type_extension.csrf'] ?? \$this->load('getForm_TypeExtension_CsrfService.php'));
    yield 5 => (\$this->privates['form.type_extension.form.data_collector'] ?? \$this->load('getForm_TypeExtension_Form_DataCollectorService.php'));
}, 6), 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => (\$this->privates['form.type_extension.repeated.validator'] ?? (\$this->privates['form.type_extension.repeated.validator'] = new \\Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => (\$this->privates['form.type_extension.submit.validator'] ?? (\$this->privates['form.type_extension.submit.validator'] = new \\Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension()));
}, 1)], new RewindableGenerator(function () {
    yield 0 => (\$this->privates['form.type_guesser.validator'] ?? \$this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => (\$this->privates['form.type_guesser.doctrine'] ?? \$this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))], new \\Symfony\\Component\\Form\\Extension\\DataCollector\\Proxy\\ResolvedTypeFactoryDataCollectorProxy(new \\Symfony\\Component\\Form\\ResolvedFormTypeFactory(), (\$this->privates['data_collector.form'] ?? \$this->getDataCollector_FormService())));
", "var/cache/dev/ContainerRWJYAMq/getForm_RegistryService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerRWJYAMq/getForm_RegistryService.php");
    }
}
