<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerEObV2MS/getMaker_AutoCommand_MakeSubscriberService.php */
class __TwigTemplate_1d03f0f6a94328fef37309f463f5fcb0be63dd811e9f91a84eb9a9d11bc787b4 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getMaker_AutoCommand_MakeSubscriberService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getMaker_AutoCommand_MakeSubscriberService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.auto_command.make_subscriber' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/Command/MakerCommand.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/MakerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/Maker/AbstractMaker.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/Maker/MakeSubscriber.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/EventRegistry.php';

\$this->privates['maker.auto_command.make_subscriber'] = \$instance = new \\Symfony\\Bundle\\MakerBundle\\Command\\MakerCommand(new \\Symfony\\Bundle\\MakerBundle\\Maker\\MakeSubscriber(new \\Symfony\\Bundle\\MakerBundle\\EventRegistry((\$this->services['event_dispatcher'] ?? \$this->getEventDispatcherService()))), (\$this->privates['maker.file_manager'] ?? \$this->load('getMaker_FileManagerService.php')), (\$this->privates['maker.generator'] ?? \$this->load('getMaker_GeneratorService.php')));

\$instance->setName('make:subscriber');

return \$instance;
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerEObV2MS/getMaker_AutoCommand_MakeSubscriberService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.auto_command.make_subscriber' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/Command/MakerCommand.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/MakerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/Maker/AbstractMaker.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/Maker/MakeSubscriber.php';
include_once \$this->targetDirs[3].'/vendor/symfony/maker-bundle/src/EventRegistry.php';

\$this->privates['maker.auto_command.make_subscriber'] = \$instance = new \\Symfony\\Bundle\\MakerBundle\\Command\\MakerCommand(new \\Symfony\\Bundle\\MakerBundle\\Maker\\MakeSubscriber(new \\Symfony\\Bundle\\MakerBundle\\EventRegistry((\$this->services['event_dispatcher'] ?? \$this->getEventDispatcherService()))), (\$this->privates['maker.file_manager'] ?? \$this->load('getMaker_FileManagerService.php')), (\$this->privates['maker.generator'] ?? \$this->load('getMaker_GeneratorService.php')));

\$instance->setName('make:subscriber');

return \$instance;
", "var/cache/dev/ContainerEObV2MS/getMaker_AutoCommand_MakeSubscriberService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerEObV2MS/getMaker_AutoCommand_MakeSubscriberService.php");
    }
}
