<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerRWJYAMq/getAnnotations_CacheService.php */
class __TwigTemplate_b7ea44d2ef4a0b00199be2c22f2109ee43a6c75fcbc73c72c3344b96fc0c0ce1 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getAnnotations_CacheService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getAnnotations_CacheService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'annotations.cache' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/cache/DoctrineProvider.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Traits/ProxyTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Traits/PhpArrayTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Adapter/PhpArrayAdapter.php';

return new \\Symfony\\Component\\Cache\\DoctrineProvider(\\Symfony\\Component\\Cache\\Adapter\\PhpArrayAdapter::create((\$this->targetDirs[0].'/annotations.php'), (\$this->privates['cache.annotations'] ?? \$this->getCache_AnnotationsService())));
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerRWJYAMq/getAnnotations_CacheService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'annotations.cache' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/cache/DoctrineProvider.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Traits/ProxyTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Traits/PhpArrayTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Adapter/PhpArrayAdapter.php';

return new \\Symfony\\Component\\Cache\\DoctrineProvider(\\Symfony\\Component\\Cache\\Adapter\\PhpArrayAdapter::create((\$this->targetDirs[0].'/annotations.php'), (\$this->privates['cache.annotations'] ?? \$this->getCache_AnnotationsService())));
", "var/cache/dev/ContainerRWJYAMq/getAnnotations_CacheService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerRWJYAMq/getAnnotations_CacheService.php");
    }
}
