<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerEObV2MS/getForm_TypeExtension_CsrfService.php */
class __TwigTemplate_2f40d3ab7209c66f81ed36beeb178372d8b68c117ca51b36a46e7ff95e6f6e91 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getForm_TypeExtension_CsrfService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getForm_TypeExtension_CsrfService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.type_extension.csrf' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/Extension/Csrf/Type/FormTypeCsrfExtension.php';

return \$this->privates['form.type_extension.csrf'] = new \\Symfony\\Component\\Form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension((\$this->services['security.csrf.token_manager'] ?? \$this->load('getSecurity_Csrf_TokenManagerService.php')), true, '_token', (\$this->services['translator'] ?? \$this->getTranslatorService()), 'validators', (\$this->privates['form.server_params'] ?? \$this->load('getForm_ServerParamsService.php')));
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerEObV2MS/getForm_TypeExtension_CsrfService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.type_extension.csrf' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/Extension/Csrf/Type/FormTypeCsrfExtension.php';

return \$this->privates['form.type_extension.csrf'] = new \\Symfony\\Component\\Form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension((\$this->services['security.csrf.token_manager'] ?? \$this->load('getSecurity_Csrf_TokenManagerService.php')), true, '_token', (\$this->services['translator'] ?? \$this->getTranslatorService()), 'validators', (\$this->privates['form.server_params'] ?? \$this->load('getForm_ServerParamsService.php')));
", "var/cache/dev/ContainerEObV2MS/getForm_TypeExtension_CsrfService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerEObV2MS/getForm_TypeExtension_CsrfService.php");
    }
}
