<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerEObV2MS/getSecurity_Firewall_Map_Context_MainService.php */
class __TwigTemplate_ae8e89bc3440c12c5d879e9b968a87014dd7cf9ed8a7b5710d5e932985b4c408 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getSecurity_Firewall_Map_Context_MainService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getSecurity_Firewall_Map_Context_MainService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.context.main' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/security-bundle/Security/FirewallContext.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Util/TargetPathTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Firewall/ExceptionListener.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Firewall/ListenerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Firewall/LegacyListenerTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Firewall/LogoutListener.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/LogoutSuccessHandlerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/DefaultLogoutSuccessHandler.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/LogoutHandlerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/CsrfTokenClearingLogoutHandler.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/SessionLogoutHandler.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

\$a = (\$this->services['security.token_storage'] ?? (\$this->services['security.token_storage'] = new \\Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorage()));
\$b = (\$this->privates['security.http_utils'] ?? \$this->load('getSecurity_HttpUtilsService.php'));
\$c = new \\Symfony\\Component\\Security\\Http\\Firewall\\LogoutListener(\$a, \$b, new \\Symfony\\Component\\Security\\Http\\Logout\\DefaultLogoutSuccessHandler(\$b, 'home'), ['csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'logout', 'logout_path' => 'security_logout']);
\$c->addHandler(new \\Symfony\\Component\\Security\\Http\\Logout\\CsrfTokenClearingLogoutHandler((\$this->privates['security.csrf.token_storage'] ?? \$this->load('getSecurity_Csrf_TokenStorageService.php'))));
\$c->addHandler(new \\Symfony\\Component\\Security\\Http\\Logout\\SessionLogoutHandler());

return \$this->privates['security.firewall.map.context.main'] = new \\Symfony\\Bundle\\SecurityBundle\\Security\\FirewallContext(new RewindableGenerator(function () {
    yield 0 => (\$this->privates['security.channel_listener'] ?? \$this->load('getSecurity_ChannelListenerService.php'));
    yield 1 => (\$this->privates['security.context_listener.0'] ?? \$this->load('getSecurity_ContextListener_0Service.php'));
    yield 2 => (\$this->privates['security.authentication.listener.form.main'] ?? \$this->load('getSecurity_Authentication_Listener_Form_MainService.php'));
    yield 3 => (\$this->privates['security.authentication.listener.basic.main'] ?? \$this->load('getSecurity_Authentication_Listener_Basic_MainService.php'));
    yield 4 => (\$this->privates['security.authentication.listener.anonymous.main'] ?? \$this->load('getSecurity_Authentication_Listener_Anonymous_MainService.php'));
    yield 5 => (\$this->privates['security.access_listener'] ?? \$this->load('getSecurity_AccessListenerService.php'));
}, 6), new \\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener(\$a, (\$this->privates['security.authentication.trust_resolver'] ?? (\$this->privates['security.authentication.trust_resolver'] = new \\Symfony\\Component\\Security\\Core\\Authentication\\AuthenticationTrustResolver(NULL, NULL))), \$b, 'main', (\$this->privates['security.authentication.form_entry_point.main'] ?? \$this->load('getSecurity_Authentication_FormEntryPoint_MainService.php')), NULL, NULL, (\$this->privates['monolog.logger.security'] ?? \$this->load('getMonolog_Logger_SecurityService.php')), false), \$c, new \\Symfony\\Bundle\\SecurityBundle\\Security\\FirewallConfig('main', 'security.user_checker', '.security.request_matcher.3UEFixr', true, false, 'security.user.provider.concrete.our_db_provider', 'main', 'security.authentication.form_entry_point.main', NULL, NULL, [0 => 'form_login', 1 => 'http_basic', 2 => 'anonymous'], NULL));
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerEObV2MS/getSecurity_Firewall_Map_Context_MainService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.context.main' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/security-bundle/Security/FirewallContext.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Util/TargetPathTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Firewall/ExceptionListener.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Firewall/ListenerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Firewall/LegacyListenerTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Firewall/LogoutListener.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/LogoutSuccessHandlerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/DefaultLogoutSuccessHandler.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/LogoutHandlerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/CsrfTokenClearingLogoutHandler.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-http/Logout/SessionLogoutHandler.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

\$a = (\$this->services['security.token_storage'] ?? (\$this->services['security.token_storage'] = new \\Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorage()));
\$b = (\$this->privates['security.http_utils'] ?? \$this->load('getSecurity_HttpUtilsService.php'));
\$c = new \\Symfony\\Component\\Security\\Http\\Firewall\\LogoutListener(\$a, \$b, new \\Symfony\\Component\\Security\\Http\\Logout\\DefaultLogoutSuccessHandler(\$b, 'home'), ['csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'logout', 'logout_path' => 'security_logout']);
\$c->addHandler(new \\Symfony\\Component\\Security\\Http\\Logout\\CsrfTokenClearingLogoutHandler((\$this->privates['security.csrf.token_storage'] ?? \$this->load('getSecurity_Csrf_TokenStorageService.php'))));
\$c->addHandler(new \\Symfony\\Component\\Security\\Http\\Logout\\SessionLogoutHandler());

return \$this->privates['security.firewall.map.context.main'] = new \\Symfony\\Bundle\\SecurityBundle\\Security\\FirewallContext(new RewindableGenerator(function () {
    yield 0 => (\$this->privates['security.channel_listener'] ?? \$this->load('getSecurity_ChannelListenerService.php'));
    yield 1 => (\$this->privates['security.context_listener.0'] ?? \$this->load('getSecurity_ContextListener_0Service.php'));
    yield 2 => (\$this->privates['security.authentication.listener.form.main'] ?? \$this->load('getSecurity_Authentication_Listener_Form_MainService.php'));
    yield 3 => (\$this->privates['security.authentication.listener.basic.main'] ?? \$this->load('getSecurity_Authentication_Listener_Basic_MainService.php'));
    yield 4 => (\$this->privates['security.authentication.listener.anonymous.main'] ?? \$this->load('getSecurity_Authentication_Listener_Anonymous_MainService.php'));
    yield 5 => (\$this->privates['security.access_listener'] ?? \$this->load('getSecurity_AccessListenerService.php'));
}, 6), new \\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener(\$a, (\$this->privates['security.authentication.trust_resolver'] ?? (\$this->privates['security.authentication.trust_resolver'] = new \\Symfony\\Component\\Security\\Core\\Authentication\\AuthenticationTrustResolver(NULL, NULL))), \$b, 'main', (\$this->privates['security.authentication.form_entry_point.main'] ?? \$this->load('getSecurity_Authentication_FormEntryPoint_MainService.php')), NULL, NULL, (\$this->privates['monolog.logger.security'] ?? \$this->load('getMonolog_Logger_SecurityService.php')), false), \$c, new \\Symfony\\Bundle\\SecurityBundle\\Security\\FirewallConfig('main', 'security.user_checker', '.security.request_matcher.3UEFixr', true, false, 'security.user.provider.concrete.our_db_provider', 'main', 'security.authentication.form_entry_point.main', NULL, NULL, [0 => 'form_login', 1 => 'http_basic', 2 => 'anonymous'], NULL));
", "var/cache/dev/ContainerEObV2MS/getSecurity_Firewall_Map_Context_MainService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerEObV2MS/getSecurity_Firewall_Map_Context_MainService.php");
    }
}
