<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerRWJYAMq/getPropertyAccessorService.php */
class __TwigTemplate_a6d8a33db5f8ee7b681d9c0fb04b54b59e49b772dd64eaf1957a0136d6aa504f extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getPropertyAccessorService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getPropertyAccessorService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'property_accessor' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/property-access/PropertyAccessorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-access/PropertyAccessor.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Traits/ArrayTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Adapter/ArrayAdapter.php';

return \$this->privates['property_accessor'] = new \\Symfony\\Component\\PropertyAccess\\PropertyAccessor(false, false, new \\Symfony\\Component\\Cache\\Adapter\\ArrayAdapter(0, false), true);
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerRWJYAMq/getPropertyAccessorService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'property_accessor' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/property-access/PropertyAccessorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-access/PropertyAccessor.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Traits/ArrayTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/cache/Adapter/ArrayAdapter.php';

return \$this->privates['property_accessor'] = new \\Symfony\\Component\\PropertyAccess\\PropertyAccessor(false, false, new \\Symfony\\Component\\Cache\\Adapter\\ArrayAdapter(0, false), true);
", "var/cache/dev/ContainerRWJYAMq/getPropertyAccessorService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerRWJYAMq/getPropertyAccessorService.php");
    }
}
