<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerRWJYAMq/getSerializerService.php */
class __TwigTemplate_f5d89dc7427477fdfa058cf65617e97a99531fd43521340235025d24d1ef7dff extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getSerializerService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getSerializerService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'serializer' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/serializer/SerializerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ContextAwareNormalizerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/DenormalizerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ContextAwareDenormalizerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/EncoderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/ContextAwareEncoderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/DecoderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/ContextAwareDecoderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Serializer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/SerializerAwareInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/CacheableSupportsMethodInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ObjectToPopulateTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/SerializerAwareTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/JsonSerializableNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/DateTimeNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ConstraintViolationListNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/NameConverter/NameConverterInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/NameConverter/AdvancedNameConverterInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/NameConverter/MetadataAwareNameConverter.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/DateIntervalNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/DataUriNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ArrayDenormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyTypeExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyDescriptionExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyAccessExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyListExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyInfoExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyInitializableExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyInfoExtractor.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Mapping/ClassDiscriminatorResolverInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Mapping/ClassDiscriminatorFromClassMetadata.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/NormalizationAwareInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/XmlEncoder.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/JsonEncoder.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/YamlEncoder.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/CsvEncoder.php';

\$a = (\$this->privates['serializer.mapping.class_metadata_factory'] ?? \$this->load('getSerializer_Mapping_ClassMetadataFactoryService.php'));

\$b = new \\Symfony\\Component\\Serializer\\NameConverter\\MetadataAwareNameConverter(\$a);

return \$this->services['serializer'] = new \\Symfony\\Component\\Serializer\\Serializer([0 => new \\Symfony\\Component\\Serializer\\Normalizer\\JsonSerializableNormalizer(), 1 => new \\Symfony\\Component\\Serializer\\Normalizer\\DateTimeNormalizer(), 2 => new \\Symfony\\Component\\Serializer\\Normalizer\\ConstraintViolationListNormalizer([], \$b), 3 => new \\Symfony\\Component\\Serializer\\Normalizer\\DateIntervalNormalizer(), 4 => new \\Symfony\\Component\\Serializer\\Normalizer\\DataUriNormalizer((\$this->privates['mime_types'] ?? \$this->load('getMimeTypesService.php'))), 5 => new \\Symfony\\Component\\Serializer\\Normalizer\\ArrayDenormalizer(), 6 => new \\Symfony\\Component\\Serializer\\Normalizer\\ObjectNormalizer(\$a, \$b, (\$this->privates['property_accessor'] ?? \$this->load('getPropertyAccessorService.php')), new \\Symfony\\Component\\PropertyInfo\\PropertyInfoExtractor(new RewindableGenerator(function () {
    yield 0 => (\$this->privates['property_info.serializer_extractor'] ?? \$this->load('getPropertyInfo_SerializerExtractorService.php'));
    yield 1 => (\$this->privates['property_info.reflection_extractor'] ?? (\$this->privates['property_info.reflection_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\ReflectionExtractor()));
    yield 2 => (\$this->privates['doctrine.orm.default_entity_manager.property_info_extractor'] ?? \$this->load('getDoctrine_Orm_DefaultEntityManager_PropertyInfoExtractorService.php'));
}, 3), new RewindableGenerator(function () {
    yield 0 => (\$this->privates['doctrine.orm.default_entity_manager.property_info_extractor'] ?? \$this->load('getDoctrine_Orm_DefaultEntityManager_PropertyInfoExtractorService.php'));
    yield 1 => (\$this->privates['property_info.php_doc_extractor'] ?? (\$this->privates['property_info.php_doc_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\PhpDocExtractor()));
    yield 2 => (\$this->privates['property_info.reflection_extractor'] ?? (\$this->privates['property_info.reflection_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\ReflectionExtractor()));
}, 3), new RewindableGenerator(function () {
    yield 0 => (\$this->privates['property_info.php_doc_extractor'] ?? (\$this->privates['property_info.php_doc_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\PhpDocExtractor()));
}, 1), new RewindableGenerator(function () {
    yield 0 => (\$this->privates['doctrine.orm.default_entity_manager.property_info_extractor'] ?? \$this->load('getDoctrine_Orm_DefaultEntityManager_PropertyInfoExtractorService.php'));
    yield 1 => (\$this->privates['property_info.reflection_extractor'] ?? (\$this->privates['property_info.reflection_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\ReflectionExtractor()));
}, 2), new RewindableGenerator(function () {
    yield 0 => (\$this->privates['property_info.reflection_extractor'] ?? (\$this->privates['property_info.reflection_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\ReflectionExtractor()));
}, 1)), new \\Symfony\\Component\\Serializer\\Mapping\\ClassDiscriminatorFromClassMetadata(\$a), NULL, [])], [0 => new \\Symfony\\Component\\Serializer\\Encoder\\XmlEncoder(), 1 => new \\Symfony\\Component\\Serializer\\Encoder\\JsonEncoder(), 2 => new \\Symfony\\Component\\Serializer\\Encoder\\YamlEncoder(), 3 => new \\Symfony\\Component\\Serializer\\Encoder\\CsvEncoder()]);
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerRWJYAMq/getSerializerService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'serializer' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/serializer/SerializerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ContextAwareNormalizerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/DenormalizerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ContextAwareDenormalizerInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/EncoderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/ContextAwareEncoderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/DecoderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/ContextAwareDecoderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Serializer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/SerializerAwareInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/CacheableSupportsMethodInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ObjectToPopulateTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/SerializerAwareTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/JsonSerializableNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/DateTimeNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ConstraintViolationListNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/NameConverter/NameConverterInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/NameConverter/AdvancedNameConverterInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/NameConverter/MetadataAwareNameConverter.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/DateIntervalNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/DataUriNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ArrayDenormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyTypeExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyDescriptionExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyAccessExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyListExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyInfoExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyInitializableExtractorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/property-info/PropertyInfoExtractor.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Mapping/ClassDiscriminatorResolverInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Mapping/ClassDiscriminatorFromClassMetadata.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/NormalizationAwareInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/XmlEncoder.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/JsonEncoder.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/YamlEncoder.php';
include_once \$this->targetDirs[3].'/vendor/symfony/serializer/Encoder/CsvEncoder.php';

\$a = (\$this->privates['serializer.mapping.class_metadata_factory'] ?? \$this->load('getSerializer_Mapping_ClassMetadataFactoryService.php'));

\$b = new \\Symfony\\Component\\Serializer\\NameConverter\\MetadataAwareNameConverter(\$a);

return \$this->services['serializer'] = new \\Symfony\\Component\\Serializer\\Serializer([0 => new \\Symfony\\Component\\Serializer\\Normalizer\\JsonSerializableNormalizer(), 1 => new \\Symfony\\Component\\Serializer\\Normalizer\\DateTimeNormalizer(), 2 => new \\Symfony\\Component\\Serializer\\Normalizer\\ConstraintViolationListNormalizer([], \$b), 3 => new \\Symfony\\Component\\Serializer\\Normalizer\\DateIntervalNormalizer(), 4 => new \\Symfony\\Component\\Serializer\\Normalizer\\DataUriNormalizer((\$this->privates['mime_types'] ?? \$this->load('getMimeTypesService.php'))), 5 => new \\Symfony\\Component\\Serializer\\Normalizer\\ArrayDenormalizer(), 6 => new \\Symfony\\Component\\Serializer\\Normalizer\\ObjectNormalizer(\$a, \$b, (\$this->privates['property_accessor'] ?? \$this->load('getPropertyAccessorService.php')), new \\Symfony\\Component\\PropertyInfo\\PropertyInfoExtractor(new RewindableGenerator(function () {
    yield 0 => (\$this->privates['property_info.serializer_extractor'] ?? \$this->load('getPropertyInfo_SerializerExtractorService.php'));
    yield 1 => (\$this->privates['property_info.reflection_extractor'] ?? (\$this->privates['property_info.reflection_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\ReflectionExtractor()));
    yield 2 => (\$this->privates['doctrine.orm.default_entity_manager.property_info_extractor'] ?? \$this->load('getDoctrine_Orm_DefaultEntityManager_PropertyInfoExtractorService.php'));
}, 3), new RewindableGenerator(function () {
    yield 0 => (\$this->privates['doctrine.orm.default_entity_manager.property_info_extractor'] ?? \$this->load('getDoctrine_Orm_DefaultEntityManager_PropertyInfoExtractorService.php'));
    yield 1 => (\$this->privates['property_info.php_doc_extractor'] ?? (\$this->privates['property_info.php_doc_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\PhpDocExtractor()));
    yield 2 => (\$this->privates['property_info.reflection_extractor'] ?? (\$this->privates['property_info.reflection_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\ReflectionExtractor()));
}, 3), new RewindableGenerator(function () {
    yield 0 => (\$this->privates['property_info.php_doc_extractor'] ?? (\$this->privates['property_info.php_doc_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\PhpDocExtractor()));
}, 1), new RewindableGenerator(function () {
    yield 0 => (\$this->privates['doctrine.orm.default_entity_manager.property_info_extractor'] ?? \$this->load('getDoctrine_Orm_DefaultEntityManager_PropertyInfoExtractorService.php'));
    yield 1 => (\$this->privates['property_info.reflection_extractor'] ?? (\$this->privates['property_info.reflection_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\ReflectionExtractor()));
}, 2), new RewindableGenerator(function () {
    yield 0 => (\$this->privates['property_info.reflection_extractor'] ?? (\$this->privates['property_info.reflection_extractor'] = new \\Symfony\\Component\\PropertyInfo\\Extractor\\ReflectionExtractor()));
}, 1)), new \\Symfony\\Component\\Serializer\\Mapping\\ClassDiscriminatorFromClassMetadata(\$a), NULL, [])], [0 => new \\Symfony\\Component\\Serializer\\Encoder\\XmlEncoder(), 1 => new \\Symfony\\Component\\Serializer\\Encoder\\JsonEncoder(), 2 => new \\Symfony\\Component\\Serializer\\Encoder\\YamlEncoder(), 3 => new \\Symfony\\Component\\Serializer\\Encoder\\CsvEncoder()]);
", "var/cache/dev/ContainerRWJYAMq/getSerializerService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerRWJYAMq/getSerializerService.php");
    }
}
