<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerEObV2MS/getTwig_Runtime_HttpkernelService.php */
class __TwigTemplate_640c9d7b537ca0cd9dac7ee9d56bd10d97e609fec2bf6accd47168709a6c3f84 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getTwig_Runtime_HttpkernelService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getTwig_Runtime_HttpkernelService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.runtime.httpkernel' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/twig-bridge/Extension/HttpKernelRuntime.php';
include_once \$this->targetDirs[3].'/vendor/symfony/http-kernel/Fragment/FragmentHandler.php';
include_once \$this->targetDirs[3].'/vendor/symfony/http-kernel/DependencyInjection/LazyLoadingFragmentHandler.php';

return \$this->privates['twig.runtime.httpkernel'] = new \\Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime(new \\Symfony\\Component\\HttpKernel\\DependencyInjection\\LazyLoadingFragmentHandler(new \\Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator(\$this->getService, [
    'inline' => ['privates', 'fragment.renderer.inline', 'getFragment_Renderer_InlineService.php', true],
], [
    'inline' => '?',
]), (\$this->services['request_stack'] ?? (\$this->services['request_stack'] = new \\Symfony\\Component\\HttpFoundation\\RequestStack())), true));
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerEObV2MS/getTwig_Runtime_HttpkernelService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.runtime.httpkernel' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/twig-bridge/Extension/HttpKernelRuntime.php';
include_once \$this->targetDirs[3].'/vendor/symfony/http-kernel/Fragment/FragmentHandler.php';
include_once \$this->targetDirs[3].'/vendor/symfony/http-kernel/DependencyInjection/LazyLoadingFragmentHandler.php';

return \$this->privates['twig.runtime.httpkernel'] = new \\Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime(new \\Symfony\\Component\\HttpKernel\\DependencyInjection\\LazyLoadingFragmentHandler(new \\Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator(\$this->getService, [
    'inline' => ['privates', 'fragment.renderer.inline', 'getFragment_Renderer_InlineService.php', true],
], [
    'inline' => '?',
]), (\$this->services['request_stack'] ?? (\$this->services['request_stack'] = new \\Symfony\\Component\\HttpFoundation\\RequestStack())), true));
", "var/cache/dev/ContainerEObV2MS/getTwig_Runtime_HttpkernelService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerEObV2MS/getTwig_Runtime_HttpkernelService.php");
    }
}
