<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/validation.php */
class __TwigTemplate_4d9650d3a3f4c3b0cee6e75694afa13e8ab16c7d8a2890de80ce2c8de963d377 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/validation.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/validation.php"));

        // line 1
        echo "<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'Symfony.Component.Form.Form' => 0,
'IteratorAggregate' => 1,
'Traversable' => 2,
'Symfony.Component.Form.FormInterface' => 3,
'ArrayAccess' => 4,
'Countable' => 5,
'Symfony.Component.Form.ClearableErrorsInterface' => 6,

], [

0 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            ((\$f = &\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories)['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
            (\$f['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\PropertyMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\PropertyMetadata'))(),
            clone (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$prototypes['Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Constraints\\\\Form'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::p('Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Constraints\\\\Form')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\\\Component\\\\Form\\\\Form',
                    'children',
                ],
                'defaultGroup' => [
                    'Form',
                ],
                'members' => [
                    [
                        'children' => [
                            \$o[1],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'children' => \$o[1],
                    ],
                ],
                'constraints' => [
                    [
                        \$o[2],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Default' => [
                            \$o[2],
                        ],
                        'Form' => [
                            \$o[2],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'Symfony\\\\Component\\\\Form\\\\Form',
                ],
                'property' => [
                    1 => 'children',
                ],
                'cascadingStrategy' => [
                    1 => 2,
                ],
                'traversalStrategy' => [
                    1 => 1,
                ],
                'groups' => [
                    2 => [
                        'Default',
                        'Form',
                    ],
                ],
            ],
        ],
        \$o[0],
        []
    );
},
1 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'IteratorAggregate',
                ],
                'defaultGroup' => [
                    'IteratorAggregate',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
2 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Traversable',
                ],
                'defaultGroup' => [
                    'Traversable',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
3 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\\\Component\\\\Form\\\\FormInterface',
                ],
                'defaultGroup' => [
                    'FormInterface',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
4 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'ArrayAccess',
                ],
                'defaultGroup' => [
                    'ArrayAccess',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
5 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Countable',
                ],
                'defaultGroup' => [
                    'Countable',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
6 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\\\Component\\\\Form\\\\ClearableErrorsInterface',
                ],
                'defaultGroup' => [
                    'ClearableErrorsInterface',
                ],
            ],
        ],
        \$o[0],
        []
    );
},

]];
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/validation.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'Symfony.Component.Form.Form' => 0,
'IteratorAggregate' => 1,
'Traversable' => 2,
'Symfony.Component.Form.FormInterface' => 3,
'ArrayAccess' => 4,
'Countable' => 5,
'Symfony.Component.Form.ClearableErrorsInterface' => 6,

], [

0 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            ((\$f = &\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories)['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
            (\$f['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\PropertyMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\PropertyMetadata'))(),
            clone (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$prototypes['Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Constraints\\\\Form'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::p('Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Constraints\\\\Form')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\\\Component\\\\Form\\\\Form',
                    'children',
                ],
                'defaultGroup' => [
                    'Form',
                ],
                'members' => [
                    [
                        'children' => [
                            \$o[1],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'children' => \$o[1],
                    ],
                ],
                'constraints' => [
                    [
                        \$o[2],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Default' => [
                            \$o[2],
                        ],
                        'Form' => [
                            \$o[2],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'Symfony\\\\Component\\\\Form\\\\Form',
                ],
                'property' => [
                    1 => 'children',
                ],
                'cascadingStrategy' => [
                    1 => 2,
                ],
                'traversalStrategy' => [
                    1 => 1,
                ],
                'groups' => [
                    2 => [
                        'Default',
                        'Form',
                    ],
                ],
            ],
        ],
        \$o[0],
        []
    );
},
1 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'IteratorAggregate',
                ],
                'defaultGroup' => [
                    'IteratorAggregate',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
2 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Traversable',
                ],
                'defaultGroup' => [
                    'Traversable',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
3 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\\\Component\\\\Form\\\\FormInterface',
                ],
                'defaultGroup' => [
                    'FormInterface',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
4 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'ArrayAccess',
                ],
                'defaultGroup' => [
                    'ArrayAccess',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
5 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Countable',
                ],
                'defaultGroup' => [
                    'Countable',
                ],
            ],
        ],
        \$o[0],
        []
    );
},
6 => static function () {
    return \\Symfony\\Component\\VarExporter\\Internal\\Hydrator::hydrate(
        \$o = [
            (\\Symfony\\Component\\VarExporter\\Internal\\Registry::\$factories['Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'] ?? \\Symfony\\Component\\VarExporter\\Internal\\Registry::f('Symfony\\\\Component\\\\Validator\\\\Mapping\\\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\\\Component\\\\Form\\\\ClearableErrorsInterface',
                ],
                'defaultGroup' => [
                    'ClearableErrorsInterface',
                ],
            ],
        ],
        \$o[0],
        []
    );
},

]];
", "var/cache/dev/validation.php", "/var/www/public/DevLaon/templates/var/cache/dev/validation.php");
    }
}
