<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LedKf08' shared service.

return $this->privates['.service_locator.LedKf08'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
    'repoCategory' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService.php', true],
], [
    'repo' => 'App\\Repository\\ArticleRepository',
    'repoCategory' => 'App\\Repository\\CategoryRepository',
]);
