<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerEObV2MS/getConsole_Command_FormDebugService.php */
class __TwigTemplate_23bafeb3248673037f06d1a0f304e43d3140b47aa7cdfb5585739fdb641b53c6 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getConsole_Command_FormDebugService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getConsole_Command_FormDebugService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/Command/DebugCommand.php';

\$this->privates['console.command.form_debug'] = \$instance = new \\Symfony\\Component\\Form\\Command\\DebugCommand((\$this->privates['form.registry'] ?? \$this->load('getForm_RegistryService.php')), [0 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type', 1 => 'App\\\\Form', 2 => 'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\Type'], [0 => 'App\\\\Form\\\\ArticleType', 1 => 'App\\\\Form\\\\CommentType', 2 => 'App\\\\Form\\\\RegistrationType', 3 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FormType', 4 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\ChoiceType', 5 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FileType', 6 => 'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\Type\\\\EntityType'], [0 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\TransformationFailureExtension', 1 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\HttpFoundation\\\\Type\\\\FormTypeHttpFoundationExtension', 2 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Type\\\\FormTypeValidatorExtension', 3 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Type\\\\RepeatedTypeValidatorExtension', 4 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Type\\\\SubmitTypeValidatorExtension', 5 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Type\\\\UploadValidatorExtension', 6 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Csrf\\\\Type\\\\FormTypeCsrfExtension', 7 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\DataCollector\\\\Type\\\\DataCollectorTypeExtension'], [0 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\ValidatorTypeGuesser', 1 => 'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\DoctrineOrmTypeGuesser'], (\$this->privates['debug.file_link_formatter'] ?? \$this->getDebug_FileLinkFormatterService()));

\$instance->setName('debug:form');

return \$instance;
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerEObV2MS/getConsole_Command_FormDebugService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once \$this->targetDirs[3].'/vendor/symfony/form/Command/DebugCommand.php';

\$this->privates['console.command.form_debug'] = \$instance = new \\Symfony\\Component\\Form\\Command\\DebugCommand((\$this->privates['form.registry'] ?? \$this->load('getForm_RegistryService.php')), [0 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type', 1 => 'App\\\\Form', 2 => 'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\Type'], [0 => 'App\\\\Form\\\\ArticleType', 1 => 'App\\\\Form\\\\CommentType', 2 => 'App\\\\Form\\\\RegistrationType', 3 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FormType', 4 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\ChoiceType', 5 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\FileType', 6 => 'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\Type\\\\EntityType'], [0 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Core\\\\Type\\\\TransformationFailureExtension', 1 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\HttpFoundation\\\\Type\\\\FormTypeHttpFoundationExtension', 2 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Type\\\\FormTypeValidatorExtension', 3 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Type\\\\RepeatedTypeValidatorExtension', 4 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Type\\\\SubmitTypeValidatorExtension', 5 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\Type\\\\UploadValidatorExtension', 6 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Csrf\\\\Type\\\\FormTypeCsrfExtension', 7 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\DataCollector\\\\Type\\\\DataCollectorTypeExtension'], [0 => 'Symfony\\\\Component\\\\Form\\\\Extension\\\\Validator\\\\ValidatorTypeGuesser', 1 => 'Symfony\\\\Bridge\\\\Doctrine\\\\Form\\\\DoctrineOrmTypeGuesser'], (\$this->privates['debug.file_link_formatter'] ?? \$this->getDebug_FileLinkFormatterService()));

\$instance->setName('debug:form');

return \$instance;
", "var/cache/dev/ContainerEObV2MS/getConsole_Command_FormDebugService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerEObV2MS/getConsole_Command_FormDebugService.php");
    }
}
