<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerEObV2MS/getTranslation_ReaderService.php */
class __TwigTemplate_87c6272dc11950cef679167286b26fec1c3548c1074f2b26793858e385b5152e extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getTranslation_ReaderService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getTranslation_ReaderService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'translation.reader' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/translation/Reader/TranslationReaderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Reader/TranslationReader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/LoaderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/ArrayLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/FileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/PhpFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/YamlFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/XliffFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/PoFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/MoFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/QtFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/CsvFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/IcuResFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/IcuDatFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/IniFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/JsonFileLoader.php';

\$this->privates['translation.reader'] = \$instance = new \\Symfony\\Component\\Translation\\Reader\\TranslationReader();

\$a = (\$this->privates['translation.loader.yml'] ?? (\$this->privates['translation.loader.yml'] = new \\Symfony\\Component\\Translation\\Loader\\YamlFileLoader()));
\$b = (\$this->privates['translation.loader.xliff'] ?? (\$this->privates['translation.loader.xliff'] = new \\Symfony\\Component\\Translation\\Loader\\XliffFileLoader()));

\$instance->addLoader('php', (\$this->privates['translation.loader.php'] ?? (\$this->privates['translation.loader.php'] = new \\Symfony\\Component\\Translation\\Loader\\PhpFileLoader())));
\$instance->addLoader('yaml', \$a);
\$instance->addLoader('yml', \$a);
\$instance->addLoader('xlf', \$b);
\$instance->addLoader('xliff', \$b);
\$instance->addLoader('po', (\$this->privates['translation.loader.po'] ?? (\$this->privates['translation.loader.po'] = new \\Symfony\\Component\\Translation\\Loader\\PoFileLoader())));
\$instance->addLoader('mo', (\$this->privates['translation.loader.mo'] ?? (\$this->privates['translation.loader.mo'] = new \\Symfony\\Component\\Translation\\Loader\\MoFileLoader())));
\$instance->addLoader('ts', (\$this->privates['translation.loader.qt'] ?? (\$this->privates['translation.loader.qt'] = new \\Symfony\\Component\\Translation\\Loader\\QtFileLoader())));
\$instance->addLoader('csv', (\$this->privates['translation.loader.csv'] ?? (\$this->privates['translation.loader.csv'] = new \\Symfony\\Component\\Translation\\Loader\\CsvFileLoader())));
\$instance->addLoader('res', (\$this->privates['translation.loader.res'] ?? (\$this->privates['translation.loader.res'] = new \\Symfony\\Component\\Translation\\Loader\\IcuResFileLoader())));
\$instance->addLoader('dat', (\$this->privates['translation.loader.dat'] ?? (\$this->privates['translation.loader.dat'] = new \\Symfony\\Component\\Translation\\Loader\\IcuDatFileLoader())));
\$instance->addLoader('ini', (\$this->privates['translation.loader.ini'] ?? (\$this->privates['translation.loader.ini'] = new \\Symfony\\Component\\Translation\\Loader\\IniFileLoader())));
\$instance->addLoader('json', (\$this->privates['translation.loader.json'] ?? (\$this->privates['translation.loader.json'] = new \\Symfony\\Component\\Translation\\Loader\\JsonFileLoader())));

return \$instance;
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerEObV2MS/getTranslation_ReaderService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'translation.reader' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/translation/Reader/TranslationReaderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Reader/TranslationReader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/LoaderInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/ArrayLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/FileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/PhpFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/YamlFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/XliffFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/PoFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/MoFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/QtFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/CsvFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/IcuResFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/IcuDatFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/IniFileLoader.php';
include_once \$this->targetDirs[3].'/vendor/symfony/translation/Loader/JsonFileLoader.php';

\$this->privates['translation.reader'] = \$instance = new \\Symfony\\Component\\Translation\\Reader\\TranslationReader();

\$a = (\$this->privates['translation.loader.yml'] ?? (\$this->privates['translation.loader.yml'] = new \\Symfony\\Component\\Translation\\Loader\\YamlFileLoader()));
\$b = (\$this->privates['translation.loader.xliff'] ?? (\$this->privates['translation.loader.xliff'] = new \\Symfony\\Component\\Translation\\Loader\\XliffFileLoader()));

\$instance->addLoader('php', (\$this->privates['translation.loader.php'] ?? (\$this->privates['translation.loader.php'] = new \\Symfony\\Component\\Translation\\Loader\\PhpFileLoader())));
\$instance->addLoader('yaml', \$a);
\$instance->addLoader('yml', \$a);
\$instance->addLoader('xlf', \$b);
\$instance->addLoader('xliff', \$b);
\$instance->addLoader('po', (\$this->privates['translation.loader.po'] ?? (\$this->privates['translation.loader.po'] = new \\Symfony\\Component\\Translation\\Loader\\PoFileLoader())));
\$instance->addLoader('mo', (\$this->privates['translation.loader.mo'] ?? (\$this->privates['translation.loader.mo'] = new \\Symfony\\Component\\Translation\\Loader\\MoFileLoader())));
\$instance->addLoader('ts', (\$this->privates['translation.loader.qt'] ?? (\$this->privates['translation.loader.qt'] = new \\Symfony\\Component\\Translation\\Loader\\QtFileLoader())));
\$instance->addLoader('csv', (\$this->privates['translation.loader.csv'] ?? (\$this->privates['translation.loader.csv'] = new \\Symfony\\Component\\Translation\\Loader\\CsvFileLoader())));
\$instance->addLoader('res', (\$this->privates['translation.loader.res'] ?? (\$this->privates['translation.loader.res'] = new \\Symfony\\Component\\Translation\\Loader\\IcuResFileLoader())));
\$instance->addLoader('dat', (\$this->privates['translation.loader.dat'] ?? (\$this->privates['translation.loader.dat'] = new \\Symfony\\Component\\Translation\\Loader\\IcuDatFileLoader())));
\$instance->addLoader('ini', (\$this->privates['translation.loader.ini'] ?? (\$this->privates['translation.loader.ini'] = new \\Symfony\\Component\\Translation\\Loader\\IniFileLoader())));
\$instance->addLoader('json', (\$this->privates['translation.loader.json'] ?? (\$this->privates['translation.loader.json'] = new \\Symfony\\Component\\Translation\\Loader\\JsonFileLoader())));

return \$instance;
", "var/cache/dev/ContainerEObV2MS/getTranslation_ReaderService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerEObV2MS/getTranslation_ReaderService.php");
    }
}
