<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerEObV2MS/getValidator_NotCompromisedPasswordService.php */
class __TwigTemplate_b569ae0c744289d80e7882c36b78f2ad70b3b614c5ba501fa786ad9a34df990b extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getValidator_NotCompromisedPasswordService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerEObV2MS/getValidator_NotCompromisedPasswordService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'validator.not_compromised_password' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidator.php';
include_once \$this->targetDirs[3].'/vendor/symfony/validator/Constraints/NotCompromisedPasswordValidator.php';
include_once \$this->targetDirs[3].'/vendor/symfony/http-client/HttpClient.php';

\$a = \\Symfony\\Component\\HttpClient\\HttpClient::create([], 6);

\$b = new \\Symfony\\Bridge\\Monolog\\Logger('http_client');
\$b->pushProcessor((\$this->privates['debug.log_processor'] ?? \$this->getDebug_LogProcessorService()));
\$b->pushHandler((\$this->privates['monolog.handler.console'] ?? \$this->getMonolog_Handler_ConsoleService()));
\$b->pushHandler((\$this->privates['monolog.handler.main'] ?? \$this->getMonolog_Handler_MainService()));
\\Symfony\\Bundle\\FrameworkBundle\\DependencyInjection\\Compiler\\AddDebugLogProcessorPass::configureLogger(\$b);

\$a->setLogger(\$b);

return \$this->privates['validator.not_compromised_password'] = new \\Symfony\\Component\\Validator\\Constraints\\NotCompromisedPasswordValidator(\$a, 'UTF-8', true, NULL);
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerEObV2MS/getValidator_NotCompromisedPasswordService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'validator.not_compromised_password' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidator.php';
include_once \$this->targetDirs[3].'/vendor/symfony/validator/Constraints/NotCompromisedPasswordValidator.php';
include_once \$this->targetDirs[3].'/vendor/symfony/http-client/HttpClient.php';

\$a = \\Symfony\\Component\\HttpClient\\HttpClient::create([], 6);

\$b = new \\Symfony\\Bridge\\Monolog\\Logger('http_client');
\$b->pushProcessor((\$this->privates['debug.log_processor'] ?? \$this->getDebug_LogProcessorService()));
\$b->pushHandler((\$this->privates['monolog.handler.console'] ?? \$this->getMonolog_Handler_ConsoleService()));
\$b->pushHandler((\$this->privates['monolog.handler.main'] ?? \$this->getMonolog_Handler_MainService()));
\\Symfony\\Bundle\\FrameworkBundle\\DependencyInjection\\Compiler\\AddDebugLogProcessorPass::configureLogger(\$b);

\$a->setLogger(\$b);

return \$this->privates['validator.not_compromised_password'] = new \\Symfony\\Component\\Validator\\Constraints\\NotCompromisedPasswordValidator(\$a, 'UTF-8', true, NULL);
", "var/cache/dev/ContainerEObV2MS/getValidator_NotCompromisedPasswordService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerEObV2MS/getValidator_NotCompromisedPasswordService.php");
    }
}
