<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerRWJYAMq/getArticleControllerService.php */
class __TwigTemplate_67a9b4591859ba94a1d8808e17193f50f2a258fcf59b8b7d5a88dd54ad1515a2 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getArticleControllerService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getArticleControllerService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\\Controller\\ArticleController' shared autowired service.

include_once \$this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once \$this->targetDirs[3].'/src/Controller/ArticleController.php';

\$this->services['App\\\\Controller\\\\ArticleController'] = \$instance = new \\App\\Controller\\ArticleController();

\$instance->setContainer((\$this->privates['.service_locator.CDOTD6.'] ?? \$this->load('get_ServiceLocator_CDOTD6_Service.php'))->withContext('App\\\\Controller\\\\ArticleController', \$this));

return \$instance;
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerRWJYAMq/getArticleControllerService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\\Controller\\ArticleController' shared autowired service.

include_once \$this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \$this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once \$this->targetDirs[3].'/src/Controller/ArticleController.php';

\$this->services['App\\\\Controller\\\\ArticleController'] = \$instance = new \\App\\Controller\\ArticleController();

\$instance->setContainer((\$this->privates['.service_locator.CDOTD6.'] ?? \$this->load('get_ServiceLocator_CDOTD6_Service.php'))->withContext('App\\\\Controller\\\\ArticleController', \$this));

return \$instance;
", "var/cache/dev/ContainerRWJYAMq/getArticleControllerService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerRWJYAMq/getArticleControllerService.php");
    }
}
