<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* var/cache/dev/ContainerRWJYAMq/getDebug_Security_Voter_Security_Access_ExpressionVoterService.php */
class __TwigTemplate_9ff18f4811289e6d1e8d60230b5dd7e9e1cd2085751d2596c4c7b0d83315a089 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getDebug_Security_Voter_Security_Access_ExpressionVoterService.php"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "var/cache/dev/ContainerRWJYAMq/getDebug_Security_Voter_Security_Access_ExpressionVoterService.php"));

        // line 1
        echo "<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.security.access.expression_voter' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/ExpressionVoter.php';

return \$this->privates['debug.security.voter.security.access.expression_voter'] = new \\Symfony\\Component\\Security\\Core\\Authorization\\Voter\\TraceableVoter(new \\Symfony\\Component\\Security\\Core\\Authorization\\Voter\\ExpressionVoter(new \\Symfony\\Component\\Security\\Core\\Authorization\\ExpressionLanguage((\$this->privates['cache.security_expression_language'] ?? \$this->getCache_SecurityExpressionLanguageService())), (\$this->privates['security.authentication.trust_resolver'] ?? (\$this->privates['security.authentication.trust_resolver'] = new \\Symfony\\Component\\Security\\Core\\Authentication\\AuthenticationTrustResolver(NULL, NULL))), (\$this->services['security.authorization_checker'] ?? \$this->getSecurity_AuthorizationCheckerService()), (\$this->privates['security.role_hierarchy'] ?? \$this->getSecurity_RoleHierarchyService())), (\$this->services['event_dispatcher'] ?? \$this->getEventDispatcherService()));
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "var/cache/dev/ContainerRWJYAMq/getDebug_Security_Voter_Security_Access_ExpressionVoterService.php";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

use Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator;
use Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.security.access.expression_voter' shared service.

include_once \$this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
include_once \$this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/ExpressionVoter.php';

return \$this->privates['debug.security.voter.security.access.expression_voter'] = new \\Symfony\\Component\\Security\\Core\\Authorization\\Voter\\TraceableVoter(new \\Symfony\\Component\\Security\\Core\\Authorization\\Voter\\ExpressionVoter(new \\Symfony\\Component\\Security\\Core\\Authorization\\ExpressionLanguage((\$this->privates['cache.security_expression_language'] ?? \$this->getCache_SecurityExpressionLanguageService())), (\$this->privates['security.authentication.trust_resolver'] ?? (\$this->privates['security.authentication.trust_resolver'] = new \\Symfony\\Component\\Security\\Core\\Authentication\\AuthenticationTrustResolver(NULL, NULL))), (\$this->services['security.authorization_checker'] ?? \$this->getSecurity_AuthorizationCheckerService()), (\$this->privates['security.role_hierarchy'] ?? \$this->getSecurity_RoleHierarchyService())), (\$this->services['event_dispatcher'] ?? \$this->getEventDispatcherService()));
", "var/cache/dev/ContainerRWJYAMq/getDebug_Security_Voter_Security_Access_ExpressionVoterService.php", "/var/www/public/DevLaon/templates/var/cache/dev/ContainerRWJYAMq/getDebug_Security_Voter_Security_Access_ExpressionVoterService.php");
    }
}
